### ISSUE TITLE
How to build a react tablet (vite) in the sim?

### ISSUE THREAD

**Issue by Jules010209** [Tacotakedown/Ouroboros-Jets-EFB#5]
Hello, I saw that you didn't want to copy the script to convert in the simulation but I haven't found a similar one anywhere. Do you think you could help me?

**Comment by Tacotakedown** [comment]
Sorry I have been away for quite a while, we currently use [this bundler](https://github.com/synapticsim/mach) to build for the sim. The usage is well documented on the provided repository for both react projects and avionics frameworks projects
